package no.moller.evp.model.ejb;

import java.rmi.RemoteException;
import java.util.*;
import javax.ejb.*;
import no.moller.evp.model.data.EVPAppointmentData;
import no.moller.util.EvpUtils;


/**
 * Bean implementation class for Enterprise Bean: Appointment
 */
public class AppointmentBean implements javax.ejb.EntityBean, no.moller.evp.model.ejb.AppointmentData.Store
{
	private final static boolean DEBUG = false;
	private java.util.Vector v = new Vector();
	private String tempFnr;
	//-----------------------------------------------------------------------------
	//
	// allocatedRes contains resourceID's for all resource tied to this appointment
	// 				 on the form: "1 4 23 12 653"
	public String allocatedRes;
	public String appointmentID;
	public String carChassisNumber;
	public int carKm;
	public String carRegNumber;
	public String changedBy;
	public String createdBy;
	public String customerAddress;
	public String customerEmail;
	public String customerName;
	public String customerTlf;
	public String customerTlfToday;
	public String dateChanged;
	public String dateCreated;
	public String endTime;
	private javax.ejb.EntityContext entityContext = null;
	public String fnr;
	public int intStatus1 = 0;
	public int intStatus2 = 0;
	public float invoicePrice = 0;
	public int jobStatus;
	public int mainResource;
	public boolean mechanicianControl = false;
	public int mechanicianStatus;
	public boolean orderConnected = false;
	public String orderText;
	public int partsStatus;
	public boolean qualityControl = false;
	private final static long serialVersionUID = 3206093459760846163L;
	public String startTime;
	public String strStatus1 = null;
	public String strStatus2 = null;
	public java.sql.Timestamp timeStampCreated;
	public String comment;
	public int serieID;
	public int appointmentType;
	public int eventtype;
	public boolean customerWaiting;
	public String interruptedDescription;
	/**
	 * Implementation field for persistent attribute: OppdragNr
	 */
	public short OppdragNr;
	/**
	 * Implementation field for persistent attribute: gjgNr
	 */
	public int gjgNr;
	/**
	 * Implementation field for persistent attribute: gjgAar
	 */
	public short gjgAar;
	/**
	 * Implementation field for persistent attribute: mverkOrderNumber
	 */
	public java.lang.String mverkOrderNumber;

	/**
	 * Implementation field for persistent attribute: appSubtypeLimit
	 */
	public java.lang.String appSubtypeLimit;
	/**
	 * Implementation field for persistent attribute: appSubtype
	 */
	public int appSubtype;
	/**
	 * Implementation field for persistent attribute: appSubTypeStatus
	 */
	public int appSubTypeStatus;
	/**
	 * Implementation field for persistent attribute: soldHoursAmount
	 */
	public double soldHoursAmount;
	/**
	 * Implementation field for persistent attribute: holidayCode
	 */
	public java.lang.String holidayCode;
	/**
	 * Implementation field for persistent attribute: authorized
	 */
	public boolean authorized;
	/**
	 * Implementation field for persistent attribute: authorizedDate
	 */
	public java.util.Date authorizedDate;
	/**
	 * Implementation field for persistent attribute: hasVcoInSession
	 */
	public boolean hasVcoInSession;
	/**
	 * This method was generated by the VisualAge for Java EJB AccessBean tool.
	 */
	/* WARNING: THIS METHOD WILL BE REGENERATED. */
	public java.util.Hashtable _copyFromEJB()
	{
		com.ibm.ivj.ejb.runtime.AccessBeanHashtable h = new com.ibm.ivj.ejb.runtime.AccessBeanHashtable();
		h.put("customerAddress", getCustomerAddress());
		h.put("jobStatus", new Integer(getJobStatus()));
		h.put("startTime", getStartTime());
		h.put("mechanicianStatus", new Integer(getMechanicianStatus()));
		h.put("allocatedRes", getAllocatedRes());
		h.put("dateCreated", getDateCreated());
		h.put("intStatus2", new Integer(getIntStatus2()));
		h.put("intStatus1", new Integer(getIntStatus1()));
		h.put("mainResource", new Integer(getMainResource()));
		h.put("customerWaiting", new Boolean(getCustomerWaiting()));
		h.put("eventtype", new Integer(getEventtype()));
		h.put("comment", getComment());
		h.put("customerName", getCustomerName());
		h.put("qualityControl", new Boolean(getQualityControl()));
		h.put("orderText", getOrderText());
		h.put("appointmentType", new Integer(getAppointmentType()));
		h.put("timeStampCreated", getTimeStampCreated());
		h.put("dateChanged", getDateChanged());
		h.put("invoicePrice", new Float(getInvoicePrice()));
		h.put("gjgAar", new Short(getGjgAar()));
		h.put("gjgNr", new Integer(getGjgNr()));
		h.put("carKm", new Integer(getCarKm()));
		h.put("endTime", getEndTime());
		h.put("orderConnected", new Boolean(getOrderConnected()));
		h.put("partsStatus", new Integer(getPartsStatus()));
		h.put("strStatus2", getStrStatus2());
		h.put("strStatus1", getStrStatus1());
		h.put("changedBy", getChangedBy());
		h.put("mechanicianControl", new Boolean(getMechanicianControl()));
		h.put("customerTlf", getCustomerTlf());
		h.put("interruptedDescription", getInterruptedDescription());
		h.put("createdBy", getCreatedBy());
		h.put("customerTlfToday", getCustomerTlfToday());
		h.put("customerEmail", getCustomerEmail());
		h.put("carRegNumber", getCarRegNumber());
		h.put("carChassisNumber", getCarChassisNumber());
		h.put("serieID", new Integer(getSerieID()));
		h.put("__Key", getEntityContext().getPrimaryKey());
		return h;
	}

	/**
	 * This method was generated by the VisualAge for Java EJB AccessBean tool.
	 */
	/* WARNING: THIS METHOD WILL BE REGENERATED. */
	public void _copyToEJB(java.util.Hashtable h)
	{
		java.lang.String localCustomerAddress = (java.lang.String) h.get("customerAddress");
		Integer localJobStatus = (Integer) h.get("jobStatus");
		java.lang.String localStartTime = (java.lang.String) h.get("startTime");
		Integer localMechanicianStatus = (Integer) h.get("mechanicianStatus");
		java.lang.String localAllocatedRes = (java.lang.String) h.get("allocatedRes");
		java.lang.String localDateCreated = (java.lang.String) h.get("dateCreated");
		Integer localIntStatus2 = (Integer) h.get("intStatus2");
		Integer localIntStatus1 = (Integer) h.get("intStatus1");
		Integer localMainResource = (Integer) h.get("mainResource");
		Boolean localCustomerWaiting = (Boolean) h.get("customerWaiting");
		Integer localEventtype = (Integer) h.get("eventtype");
		java.lang.String localComment = (java.lang.String) h.get("comment");
		java.lang.String localCustomerName = (java.lang.String) h.get("customerName");
		Boolean localQualityControl = (Boolean) h.get("qualityControl");
		java.lang.String localOrderText = (java.lang.String) h.get("orderText");
		Integer localAppointmentType = (Integer) h.get("appointmentType");
		java.sql.Timestamp localTimeStampCreated = (java.sql.Timestamp) h.get("timeStampCreated");
		java.lang.String localDateChanged = (java.lang.String) h.get("dateChanged");
		Float localInvoicePrice = (Float) h.get("invoicePrice");
		java.lang.Short localGjgAar = (java.lang.Short) h.get("gjgAar");
		java.lang.Integer localGjgNr = (java.lang.Integer) h.get("gjgNr");
		Integer localCarKm = (Integer) h.get("carKm");
		java.lang.String localEndTime = (java.lang.String) h.get("endTime");
		Boolean localOrderConnected = (Boolean) h.get("orderConnected");
		Integer localPartsStatus = (Integer) h.get("partsStatus");
		java.lang.String localStrStatus2 = (java.lang.String) h.get("strStatus2");
		java.lang.String localStrStatus1 = (java.lang.String) h.get("strStatus1");
		java.lang.String localChangedBy = (java.lang.String) h.get("changedBy");
		Boolean localMechanicianControl = (Boolean) h.get("mechanicianControl");
		java.lang.String localCustomerTlf = (java.lang.String) h.get("customerTlf");
		java.lang.String localInterruptedDescription = (java.lang.String) h.get("interruptedDescription");
		java.lang.String localCreatedBy = (java.lang.String) h.get("createdBy");
		java.lang.String localCustomerTlfToday = (java.lang.String) h.get("customerTlfToday");
		java.lang.String localCustomerEmail = (java.lang.String) h.get("customerEmail");
		java.lang.String localCarRegNumber = (java.lang.String) h.get("carRegNumber");
		java.lang.String localCarChassisNumber = (java.lang.String) h.get("carChassisNumber");
		Integer localSerieID = (Integer) h.get("serieID");
		if (h.containsKey("customerAddress")) setCustomerAddress((localCustomerAddress));
		if (h.containsKey("jobStatus")) setJobStatus((localJobStatus).intValue());
		if (h.containsKey("startTime")) setStartTime((localStartTime));
		if (h.containsKey("mechanicianStatus")) setMechanicianStatus((localMechanicianStatus).intValue());
		if (h.containsKey("allocatedRes")) setAllocatedRes((localAllocatedRes));
		if (h.containsKey("dateCreated")) setDateCreated((localDateCreated));
		if (h.containsKey("intStatus2")) setIntStatus2((localIntStatus2).intValue());
		if (h.containsKey("intStatus1")) setIntStatus1((localIntStatus1).intValue());
		if (h.containsKey("mainResource")) setMainResource((localMainResource).intValue());
		if (h.containsKey("customerWaiting")) setCustomerWaiting((localCustomerWaiting).booleanValue());
		if (h.containsKey("eventtype")) setEventtype((localEventtype).intValue());
		if (h.containsKey("comment")) setComment((localComment));
		if (h.containsKey("customerName")) setCustomerName((localCustomerName));
		if (h.containsKey("qualityControl")) setQualityControl((localQualityControl).booleanValue());
		if (h.containsKey("orderText")) setOrderText((localOrderText));
		if (h.containsKey("appointmentType")) setAppointmentType((localAppointmentType).intValue());
		if (h.containsKey("timeStampCreated")) setTimeStampCreated((localTimeStampCreated));
		if (h.containsKey("dateChanged")) setDateChanged((localDateChanged));
		if (h.containsKey("invoicePrice")) setInvoicePrice((localInvoicePrice).floatValue());
		if (h.containsKey("gjgAar")) setGjgAar((localGjgAar.shortValue()));
		if (h.containsKey("gjgNr")) setGjgNr((localGjgNr.intValue()));
		if (h.containsKey("carKm")) setCarKm((localCarKm).intValue());
		if (h.containsKey("endTime")) setEndTime((localEndTime));
		if (h.containsKey("orderConnected")) setOrderConnected((localOrderConnected).booleanValue());
		if (h.containsKey("partsStatus")) setPartsStatus((localPartsStatus).intValue());
		if (h.containsKey("strStatus2")) setStrStatus2((localStrStatus2));
		if (h.containsKey("strStatus1")) setStrStatus1((localStrStatus1));
		if (h.containsKey("changedBy")) setChangedBy((localChangedBy));
		if (h.containsKey("mechanicianControl")) setMechanicianControl((localMechanicianControl).booleanValue());
		if (h.containsKey("customerTlf")) setCustomerTlf((localCustomerTlf));
		if (h.containsKey("interruptedDescription")) setInterruptedDescription((localInterruptedDescription));
		if (h.containsKey("createdBy")) setCreatedBy((localCreatedBy));
		if (h.containsKey("customerTlfToday")) setCustomerTlfToday((localCustomerTlfToday));
		if (h.containsKey("customerEmail")) setCustomerEmail((localCustomerEmail));
		if (h.containsKey("carRegNumber")) setCarRegNumber((localCarRegNumber));
		if (h.containsKey("carChassisNumber")) setCarChassisNumber((localCarChassisNumber));
		if (h.containsKey("serieID")) setSerieID((localSerieID).intValue());
	}

	/**
	 * This method was generated for supporting the associations.
	 * @return java.util.Vector
	 */
	/* WARNING: THIS METHOD WILL BE REGENERATED. */
	protected java.util.Vector _getLinks()
	{
		java.util.Vector links = new java.util.Vector();
		return links;
	}

	/**
	 * This method was generated for supporting the associations.
	 */
	/* WARNING: THIS METHOD WILL BE REGENERATED. */
	protected void _initLinks()
	{
	}

	/**
	 * This method was generated for supporting the associations.
	 * @exception java.rmi.RemoteException The exception description.
	 * @exception javax.ejb.RemoveException The exception description.
	 */
	/* WARNING: THIS METHOD WILL BE REGENERATED. */
	protected void _removeLinks() throws java.rmi.RemoteException, javax.ejb.RemoveException
	{
		java.util.Enumeration links = _getLinks().elements();
		while (links.hasMoreElements())
		{
			try
			{
				((com.ibm.ivj.ejb.associations.interfaces.Link) (links.nextElement())).remove();
			}
			catch (javax.ejb.FinderException e)
			{
			} //Consume Finder error since I am going away
		}
	}

	/**
	 * ejbActivate method comment
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbActivate() throws java.rmi.RemoteException
	{
		_initLinks();
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, short argGjgAar, int argGjgNr, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCreatedBy, String argDateCreated, String argComment) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 2");
		// All CMP fields should be initialized here.
		//	System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		gjgAar = argGjgAar;
		gjgNr = argGjgNr;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, short argGjgAar, int argGjgNr, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 2");
		// All CMP fields should be initialized here.
		//	System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		gjgAar = argGjgAar;
		gjgNr = argGjgNr;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, short argGjgAar, int argGjgNr, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		gjgAar = argGjgAar;
		gjgNr = argGjgNr;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, short argGjgAar, int argGjgNr, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		gjgAar = argGjgAar;
		gjgNr = argGjgNr;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, short argGjgAar, int argGjgNr, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType, int argEventType) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		gjgAar = argGjgAar;
		gjgNr = argGjgNr;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
		eventtype = argEventType;
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, short argGjgAar, int argGjgNr, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType, int argEventType, boolean argCustomerWaiting, String argInterruptedDescription)
		throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		gjgAar = argGjgAar;
		gjgNr = argGjgNr;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
		eventtype = argEventType;
		customerWaiting = argCustomerWaiting;
		interruptedDescription = argInterruptedDescription;
	}

	// ================================== LEGACY MVK CREATE METHODS ==========================
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, String argMverkOrderNumber, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCreatedBy, String argDateCreated, String argComment) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 2");
		// All CMP fields should be initialized here.
		//	   System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	   System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	   appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		mverkOrderNumber = argMverkOrderNumber;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, String argMverkOrderNumber, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 2");
		// All CMP fields should be initialized here.
		//	   System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	   System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	   appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		mverkOrderNumber = argMverkOrderNumber;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, String argMverkOrderNumber, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	   System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	   System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	   appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		mverkOrderNumber = argMverkOrderNumber;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, String argMverkOrderNumber, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	   System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	   System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	   appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		mverkOrderNumber = argMverkOrderNumber;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, String argMverkOrderNumber, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType, int argEventType) throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	   System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	   System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	   appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		mverkOrderNumber = argMverkOrderNumber;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
		eventtype = argEventType;
	}

	/**
	 * ejbCreate method for a CMP entity bean
	 * @param argAppointmentID int
	 * @param argFnr java.lang.String
	 * @exception javax.ejb.CreateException The exception description.
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbCreate(String argFnr, int argMainResource, String argStartTime, String argEndTime, String argMverkOrderNumber, boolean argOrderConnected, float argPrice, int argJobStat, int argMechStat, int argPartsStat, boolean argQControl, boolean argMControl,
		String argAllocRes, String argCustomerName, String argCarRegNumber, String argCreatedBy, String argDateCreated, String argComment, int argSerieID, int argType, int argEventType, boolean argCustomerWaiting, String argInterruptedDescription)
		throws javax.ejb.CreateException, java.rmi.RemoteException
	{
		_initLinks();
		if (DEBUG) System.out.println(this.getClass() + ": ejbCreate 3");
		// All CMP fields should be initialized here.
		//	   System.out.println("Create 1");
		/*
		 * int nextID = 0; try{ nextID = getNextAppointmentID(); } catch (FinderException e) { System.out.println("Error finding newest appointment" + e); throw (new CreateException("Error finding newest appointment")); }
		 */
		//	   System.out.println("Create 2");
		tempFnr = argFnr;
		String sUID = getUID(EvpUtils.getCalendar(argStartTime, -1));
		//	   appointmentID = nextID;
		appointmentID = sUID;
		fnr = argFnr;
		mainResource = argMainResource;
		startTime = argStartTime;
		endTime = argEndTime;
		mverkOrderNumber = argMverkOrderNumber;
		orderConnected = argOrderConnected;
		invoicePrice = argPrice;
		jobStatus = argJobStat;
		mechanicianStatus = argMechStat;
		partsStatus = argPartsStat;
		qualityControl = argQControl;
		mechanicianControl = argMControl;
		allocatedRes = argAllocRes;
		customerName = argCustomerName;
		carRegNumber = argCarRegNumber;
		createdBy = argCreatedBy;
		dateCreated = argDateCreated;
		comment = argComment;
		timeStampCreated = new java.sql.Timestamp(System.currentTimeMillis());
		appointmentType = argType;
		serieID = argSerieID;
		eventtype = argEventType;
		customerWaiting = argCustomerWaiting;
		interruptedDescription = argInterruptedDescription;
	}

	// ==================== END LEGACY EJBCREATE METHODS =========================================
	/**
	 * ejbLoad method comment
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbLoad() throws java.rmi.RemoteException
	{
		_initLinks();
	}

	/**
	 * ejbPassivate method comment
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbPassivate() throws java.rmi.RemoteException
	{
	}

	/**
	 * ejbRemove method comment
	 * @exception java.rmi.RemoteException The exception description.
	 * @exception javax.ejb.RemoveException The exception description.
	 */
	public void ejbRemove() throws java.rmi.RemoteException, javax.ejb.RemoveException
	{
		_removeLinks();
	}

	/**
	 * ejbStore method comment
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void ejbStore() throws java.rmi.RemoteException
	{
	}

	/**
	 * Getter method for allocatedRes
	 * @return java.lang.String
	 */
	public java.lang.String getAllocatedRes()
	{
		return allocatedRes;
	}

	/**
	 * Getter method for appointmentType
	 */
	public int getAppointmentType()
	{
		return appointmentType;
	}

	/**
	 * Getter method for carChassisNumber
	 * @return java.lang.String
	 */
	public java.lang.String getCarChassisNumber()
	{
		return carChassisNumber;
	}

	/**
	 * Getter method for carKm
	 * @return int
	 */
	public int getCarKm()
	{
		return carKm;
	}

	/**
	 * Getter method for carRegNumber
	 * @return java.lang.String
	 */
	public java.lang.String getCarRegNumber()
	{
		return carRegNumber;
	}

	/**
	 * Getter method for changedBy
	 * @return java.lang.String
	 */
	public java.lang.String getChangedBy()
	{
		return changedBy;
	}

	/**
	 * Getter method for comment
	 */
	public java.lang.String getComment()
	{
		return comment;
	}

	/**
	 * Getter method for createdBy
	 * @return java.lang.String
	 */
	public java.lang.String getCreatedBy()
	{
		return createdBy;
	}

	/**
	 * Getter method for customerAddress
	 * @return java.lang.String
	 */
	public java.lang.String getCustomerAddress()
	{
		return customerAddress;
	}

	/**
	 * Getter method for customerEmail
	 * @return java.lang.String
	 */
	public java.lang.String getCustomerEmail()
	{
		return customerEmail;
	}

	/**
	 * Getter method for customerName
	 * @return java.lang.String
	 */
	public java.lang.String getCustomerName()
	{
		return customerName;
	}

	/**
	 * Getter method for customerTlf
	 * @return java.lang.String
	 */
	public java.lang.String getCustomerTlf()
	{
		return customerTlf;
	}

	/**
	 * Getter method for customerTlfToday
	 * @return java.lang.String
	 */
	public java.lang.String getCustomerTlfToday()
	{
		return customerTlfToday;
	}

	/**
	 * Getter method for customerWaiting
	 */
	public boolean getCustomerWaiting()
	{
		return customerWaiting;
	}

	/**
	 * Getter method for dateChanged
	 * @return java.lang.String
	 */
	public java.lang.String getDateChanged()
	{
		return dateChanged;
	}

	/**
	 * Getter method for dateCreated
	 * @return java.lang.String
	 */
	public java.lang.String getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Getter method for endTime
	 * @return java.lang.String
	 */
	public java.lang.String getEndTime()
	{
		return endTime;
	}

	/**
	 * getEntityContext method comment
	 * @return javax.ejb.EntityContext
	 */
	public javax.ejb.EntityContext getEntityContext()
	{
		return entityContext;
	}

	/**
	 * Getter method for eventtype
	 */
	public int getEventtype()
	{
		return eventtype;
	}

	/**
	 * Getter method for interruptedDescription
	 */
	public java.lang.String getInterruptedDescription()
	{
		return interruptedDescription;
	}

	/**
	 * Getter method for intStatus1
	 * @return int
	 */
	public int getIntStatus1()
	{
		return intStatus1;
	}

	/**
	 * Getter method for intStatus2
	 * @return int
	 */
	public int getIntStatus2()
	{
		return intStatus2;
	}

	/**
	 * Getter method for invoicePrice
	 * @return float
	 */
	public float getInvoicePrice()
	{
		return invoicePrice;
	}

	/**
	 * Getter method for jobStatus
	 * @return int
	 */
	public int getJobStatus()
	{
		return jobStatus;
	}

	/**
	 * Getter method for mainResource
	 * @return int
	 */
	public int getMainResource()
	{
		return mainResource;
	}

	/**
	 * Getter method for mechanicianControl
	 * @return boolean
	 */
	public boolean getMechanicianControl()
	{
		return mechanicianControl;
	}

	/**
	 * Getter method for mechanicianStatus
	 * @return int
	 */
	public int getMechanicianStatus()
	{
		return mechanicianStatus;
	}

	/**
	 * Getter method for orderConnected
	 * @return boolean
	 */
	public boolean getOrderConnected()
	{
		return orderConnected;
	}

	/**
	 * Getter method for orderText
	 * @return java.lang.String
	 */
	public java.lang.String getOrderText()
	{
		return orderText;
	}

	/**
	 * Getter method for partsStatus
	 * @return int
	 */
	public int getPartsStatus()
	{
		return partsStatus;
	}

	/**
	 * Getter method for qualityControl
	 * @return boolean
	 */
	public boolean getQualityControl()
	{
		return qualityControl;
	}

	/**
	 * Getter method for serieID
	 */
	public int getSerieID()
	{
		return serieID;
	}

	/**
	 * Getter method for startTime
	 * @return java.lang.String
	 */
	public java.lang.String getStartTime()
	{
		return startTime;
	}

	/**
	 * Getter method for strStatus1
	 * @return java.lang.String
	 */
	public java.lang.String getStrStatus1()
	{
		return strStatus1;
	}

	/**
	 * Getter method for strStatus2
	 * @return java.lang.String
	 */
	public java.lang.String getStrStatus2()
	{
		return strStatus2;
	}

	/**
	 * Getter method for timeStampCreated
	 * @return java.sql.Timestamp
	 */
	public java.sql.Timestamp getTimeStampCreated()
	{
		return timeStampCreated;
	}

	/**
	 * Insert the method's description here. Creation date: (03.05.2001 15:21:55)
	 * @return java.lang.String
	 * @param cal java.util.Calendar
	 */
	private String getUID(Calendar cal)
	{
		String id = EvpUtils.getDateString(cal, "yyyyMMdd", false);
		//	Vector v = new Vector();
		try
		{
			Enumeration en = ((AppointmentHome) getEntityContext().getEJBHome()).findAppointmentsOnDay(tempFnr, id);
			while (en.hasMoreElements())
			{
				Appointment app = (Appointment) javax.rmi.PortableRemoteObject.narrow(en.nextElement(), Appointment.class);
				v.addElement(new EVPAppointmentData(tempFnr, ((AppointmentKey) app.getPrimaryKey()).appointmentID, 
					app.getStartTime(), app.getEndTime()));
			}
		}
		catch (ObjectNotFoundException e)
		{
			//		System.out.println(this.getClass() + "->>> ");
			//		e.printStackTrace();
		}
		catch (FinderException e)
		{
			//		System.out.println(this.getClass() + "->>> ");
			//		e.printStackTrace();
		}
		catch (RemoteException e)
		{
			//		System.out.println(this.getClass() + "->>> ");
			//		e.printStackTrace();
		}
		// Aldri mer enn 1000 avtaler på en dag ???
		for (int i = 1; i < 1000; i++)
		{
			if (getUIDPosition(id + Integer.toString(i)) == -1)
			{
				id = id + Integer.toString(i);
				break;
			}
		}
		return id;
	}

	/**
	 * This method returns the position of the element containing the passed UID.
	 * @param id The UID that needs to be searched for.
	 * @returns The position of the element that contains the given UID. -1 if no match found.
	 */
	private int getUIDPosition(String id)
	{
		int pos = -1;
		//	int pos = 10;
		for (int i = 0; i < v.size(); i++)
		{
			if (((EVPAppointmentData) v.elementAt(i)).containsUID(id))
			{
				pos = i;
				break;
			}
		}
		return pos;
	}

	/**
	 * Setter method for allocatedRes
	 * @param newValue java.lang.String
	 */
	public void setAllocatedRes(java.lang.String newValue)
	{
		this.allocatedRes = newValue;
	}

	/**
	 * Setter method for appointmentType
	 */
	public void setAppointmentType(int newValue)
	{
		this.appointmentType = newValue;
	}

	/**
	 * Setter method for carChassisNumber
	 * @param newValue java.lang.String
	 */
	public void setCarChassisNumber(java.lang.String newValue)
	{
		this.carChassisNumber = newValue;
	}

	/**
	 * Setter method for carKm
	 * @param newValue int
	 */
	public void setCarKm(int newValue)
	{
		this.carKm = newValue;
	}

	/**
	 * Setter method for carRegNumber
	 * @param newValue java.lang.String
	 */
	public void setCarRegNumber(java.lang.String newValue)
	{
		this.carRegNumber = newValue;
	}

	/**
	 * Setter method for changedBy
	 * @param newValue java.lang.String
	 */
	public void setChangedBy(java.lang.String newValue)
	{
		this.changedBy = newValue;
	}

	/**
	 * Setter method for comment
	 */
	public void setComment(java.lang.String newValue)
	{
		this.comment = newValue;
	}

	/**
	 * Setter method for createdBy
	 * @param newValue java.lang.String
	 */
	public void setCreatedBy(java.lang.String newValue)
	{
		this.createdBy = newValue;
	}

	/**
	 * Setter method for customerAddress
	 * @param newValue java.lang.String
	 */
	public void setCustomerAddress(java.lang.String newValue)
	{
		this.customerAddress = newValue;
	}

	/**
	 * Setter method for customerEmail
	 * @param newValue java.lang.String
	 */
	public void setCustomerEmail(java.lang.String newValue)
	{
		this.customerEmail = newValue;
	}

	/**
	 * Setter method for customerName
	 * @param newValue java.lang.String
	 */
	public void setCustomerName(java.lang.String newValue)
	{
		this.customerName = newValue;
	}

	/**
	 * Setter method for customerTlf
	 * @param newValue java.lang.String
	 */
	public void setCustomerTlf(java.lang.String newValue)
	{
		this.customerTlf = newValue;
	}

	/**
	 * Setter method for customerTlfToday
	 * @param newValue java.lang.String
	 */
	public void setCustomerTlfToday(java.lang.String newValue)
	{
		this.customerTlfToday = newValue;
	}

	/**
	 * Setter method for customerWaiting
	 */
	public void setCustomerWaiting(boolean newValue)
	{
		this.customerWaiting = newValue;
	}

	/**
	 * Setter method for dateChanged
	 * @param newValue java.lang.String
	 */
	public void setDateChanged(java.lang.String newValue)
	{
		this.dateChanged = newValue;
	}

	/**
	 * Setter method for dateCreated
	 * @param newValue java.lang.String
	 */
	public void setDateCreated(java.lang.String newValue)
	{
		this.dateCreated = newValue;
	}

	/**
	 * Setter method for endTime
	 * @param newValue java.lang.String
	 */
	public void setEndTime(java.lang.String newValue)
	{
		this.endTime = newValue;
	}

	/**
	 * setEntityContext method comment
	 * @param ctx javax.ejb.EntityContext
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void setEntityContext(javax.ejb.EntityContext ctx) throws java.rmi.RemoteException
	{
		entityContext = ctx;
	}

	/**
	 * Setter method for eventtype
	 */
	public void setEventtype(int newValue)
	{
		this.eventtype = newValue;
	}

	/**
	 * Setter method for interruptedDescription
	 */
	public void setInterruptedDescription(java.lang.String newValue)
	{
		this.interruptedDescription = newValue;
	}

	/**
	 * Setter method for intStatus1
	 * @param newValue int
	 */
	public void setIntStatus1(int newValue)
	{
		this.intStatus1 = newValue;
	}

	/**
	 * Setter method for intStatus2
	 * @param newValue int
	 */
	public void setIntStatus2(int newValue)
	{
		this.intStatus2 = newValue;
	}

	/**
	 * Setter method for invoicePrice
	 * @param newValue float
	 */
	public void setInvoicePrice(float newValue)
	{
		this.invoicePrice = newValue;
	}

	/**
	 * Setter method for jobStatus
	 * @param newValue int
	 */
	public void setJobStatus(int newValue)
	{
		this.jobStatus = newValue;
	}

	/**
	 * Setter method for mainResource
	 * @param newValue int
	 */
	public void setMainResource(int newValue)
	{
		this.mainResource = newValue;
	}

	/**
	 * Setter method for mechanicianControl
	 * @param newValue boolean
	 */
	public void setMechanicianControl(boolean newValue)
	{
		this.mechanicianControl = newValue;
	}

	/**
	 * Setter method for mechanicianStatus
	 * @param newValue int
	 */
	public void setMechanicianStatus(int newValue)
	{
		this.mechanicianStatus = newValue;
	}

	/**
	 * Setter method for orderConnected
	 * @param newValue boolean
	 */
	public void setOrderConnected(boolean newValue)
	{
		this.orderConnected = newValue;
	}

	/**
	 * Setter method for orderText
	 * @param newValue java.lang.String
	 */
	public void setOrderText(java.lang.String newValue)
	{
		this.orderText = newValue;
	}

	/**
	 * Setter method for partsStatus
	 * @param newValue int
	 */
	public void setPartsStatus(int newValue)
	{
		this.partsStatus = newValue;
	}

	/**
	 * Setter method for qualityControl
	 * @param newValue boolean
	 */
	public void setQualityControl(boolean newValue)
	{
		this.qualityControl = newValue;
	}

	/**
	 * Setter method for serieID
	 */
	public void setSerieID(int newValue)
	{
		this.serieID = newValue;
	}

	/**
	 * Setter method for startTime
	 * @param newValue java.lang.String
	 */
	public void setStartTime(java.lang.String newValue)
	{
		this.startTime = newValue;
	}

	/**
	 * Setter method for strStatus1
	 * @param newValue java.lang.String
	 */
	public void setStrStatus1(java.lang.String newValue)
	{
		this.strStatus1 = newValue;
	}

	/**
	 * Setter method for strStatus2
	 * @param newValue java.lang.String
	 */
	public void setStrStatus2(java.lang.String newValue)
	{
		this.strStatus2 = newValue;
	}

	/**
	 * Setter method for timeStampCreated
	 * @param newValue java.sql.Timestamp
	 */
	public void setTimeStampCreated(java.sql.Timestamp newValue)
	{
		this.timeStampCreated = newValue;
	}

	/**
	 * unsetEntityContext method comment
	 * @exception java.rmi.RemoteException The exception description.
	 */
	public void unsetEntityContext() throws java.rmi.RemoteException
	{
		entityContext = null;
	}

	/**
	 * Get accessor for persistent attribute: OppdragNr
	 */
	public short getOppdragNr()
	{
		return OppdragNr;
	}

	/**
	 * Set accessor for persistent attribute: OppdragNr
	 */
	public void setOppdragNr(short newOppdragNr)
	{
		OppdragNr = newOppdragNr;
	}

	/**
	 * Get accessor for persistent attribute: gjgNr
	 */
	public int getGjgNr()
	{
		return gjgNr;
	}

	/**
	 * Set accessor for persistent attribute: gjgNr
	 */
	public void setGjgNr(int newGjgNr)
	{
		gjgNr = newGjgNr;
	}

	/**
	 * Get accessor for persistent attribute: gjgAar
	 */
	public short getGjgAar()
	{
		return gjgAar;
	}

	/**
	 * Set accessor for persistent attribute: gjgAar
	 */
	public void setGjgAar(short newGjgAar)
	{
		gjgAar = newGjgAar;
	}

	/**
	 * getAppointmentData
	 */
	public no.moller.evp.model.ejb.AppointmentData getAppointmentData() {
	    return new no.moller.evp.model.ejb.AppointmentData(this);
	}

	/**
	 * setAppointmentData
	 */
	public void setAppointmentData(no.moller.evp.model.ejb.AppointmentData data) throws com.ibm.etools.ejb.client.runtime.FieldChangedException {
	    data.copyTo(this);
	    if (!data.getIsinterruptedDescriptionDirty()) {
	        if (this.getInterruptedDescription() != null && data.getInterruptedDescription() != null) {
	    	if (!this.getInterruptedDescription().equals(data.getInterruptedDescription())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getInterruptedDescription() == null && data.getInterruptedDescription() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsgjgAarDirty()) {
	        if (this.getGjgAar() != data.getGjgAar())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsserieIDDirty()) {
	        if (this.getSerieID() != data.getSerieID())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIspartsStatusDirty()) {
	        if (this.getPartsStatus() != data.getPartsStatus())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIscustomerWaitingDirty()) {
	        if (this.getCustomerWaiting() != data.getCustomerWaiting())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsstartTimeDirty()) {
	        if (this.getStartTime() != null && data.getStartTime() != null) {
	    	if (!this.getStartTime().equals(data.getStartTime())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getStartTime() == null && data.getStartTime() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsappointmentTypeDirty()) {
	        if (this.getAppointmentType() != data.getAppointmentType())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsjobStatusDirty()) {
	        if (this.getJobStatus() != data.getJobStatus())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIschangedByDirty()) {
	        if (this.getChangedBy() != null && data.getChangedBy() != null) {
	    	if (!this.getChangedBy().equals(data.getChangedBy())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getChangedBy() == null && data.getChangedBy() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIscustomerTlfDirty()) {
	        if (this.getCustomerTlf() != null && data.getCustomerTlf() != null) {
	    	if (!this.getCustomerTlf().equals(data.getCustomerTlf())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCustomerTlf() == null && data.getCustomerTlf() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsintStatus2Dirty()) {
	        if (this.getIntStatus2() != data.getIntStatus2())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsintStatus1Dirty()) {
	        if (this.getIntStatus1() != data.getIntStatus1())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsendTimeDirty()) {
	        if (this.getEndTime() != null && data.getEndTime() != null) {
	    	if (!this.getEndTime().equals(data.getEndTime())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getEndTime() == null && data.getEndTime() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsinvoicePriceDirty()) {
	        Float f1 = new Float(this.getInvoicePrice());
	        Float f2 = new Float(data.getInvoicePrice());
	        if (!f1.equals(f2))
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsorderConnectedDirty()) {
	        if (this.getOrderConnected() != data.getOrderConnected())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIscustomerTlfTodayDirty()) {
	        if (this.getCustomerTlfToday() != null && data.getCustomerTlfToday() != null) {
	    	if (!this.getCustomerTlfToday().equals(data.getCustomerTlfToday())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCustomerTlfToday() == null && data.getCustomerTlfToday() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIstimeStampCreatedDirty()) {
	        if (this.getTimeStampCreated() != null && data.getTimeStampCreated() != null) {
	    	if (!this.getTimeStampCreated().equals(data.getTimeStampCreated())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getTimeStampCreated() == null && data.getTimeStampCreated() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIseventtypeDirty()) {
	        if (this.getEventtype() != data.getEventtype())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsdateChangedDirty()) {
	        if (this.getDateChanged() != null && data.getDateChanged() != null) {
	    	if (!this.getDateChanged().equals(data.getDateChanged())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getDateChanged() == null && data.getDateChanged() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIscommentDirty()) {
	        if (this.getComment() != null && data.getComment() != null) {
	    	if (!this.getComment().equals(data.getComment())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getComment() == null && data.getComment() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsgjgNrDirty()) {
	        if (this.getGjgNr() != data.getGjgNr())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIscreatedByDirty()) {
	        if (this.getCreatedBy() != null && data.getCreatedBy() != null) {
	    	if (!this.getCreatedBy().equals(data.getCreatedBy())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCreatedBy() == null && data.getCreatedBy() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsallocatedResDirty()) {
	        if (this.getAllocatedRes() != null && data.getAllocatedRes() != null) {
	    	if (!this.getAllocatedRes().equals(data.getAllocatedRes())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getAllocatedRes() == null && data.getAllocatedRes() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsmechanicianStatusDirty()) {
	        if (this.getMechanicianStatus() != data.getMechanicianStatus())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIscustomerNameDirty()) {
	        if (this.getCustomerName() != null && data.getCustomerName() != null) {
	    	if (!this.getCustomerName().equals(data.getCustomerName())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCustomerName() == null && data.getCustomerName() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsstrStatus2Dirty()) {
	        if (this.getStrStatus2() != null && data.getStrStatus2() != null) {
	    	if (!this.getStrStatus2().equals(data.getStrStatus2())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getStrStatus2() == null && data.getStrStatus2() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsorderTextDirty()) {
	        if (this.getOrderText() != null && data.getOrderText() != null) {
	    	if (!this.getOrderText().equals(data.getOrderText())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getOrderText() == null && data.getOrderText() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsstrStatus1Dirty()) {
	        if (this.getStrStatus1() != null && data.getStrStatus1() != null) {
	    	if (!this.getStrStatus1().equals(data.getStrStatus1())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getStrStatus1() == null && data.getStrStatus1() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIscarChassisNumberDirty()) {
	        if (this.getCarChassisNumber() != null && data.getCarChassisNumber() != null) {
	    	if (!this.getCarChassisNumber().equals(data.getCarChassisNumber())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCarChassisNumber() == null && data.getCarChassisNumber() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIscustomerAddressDirty()) {
	        if (this.getCustomerAddress() != null && data.getCustomerAddress() != null) {
	    	if (!this.getCustomerAddress().equals(data.getCustomerAddress())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCustomerAddress() == null && data.getCustomerAddress() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIscustomerEmailDirty()) {
	        if (this.getCustomerEmail() != null && data.getCustomerEmail() != null) {
	    	if (!this.getCustomerEmail().equals(data.getCustomerEmail())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCustomerEmail() == null && data.getCustomerEmail() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsmainResourceDirty()) {
	        if (this.getMainResource() != data.getMainResource())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsdateCreatedDirty()) {
	        if (this.getDateCreated() != null && data.getDateCreated() != null) {
	    	if (!this.getDateCreated().equals(data.getDateCreated())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getDateCreated() == null && data.getDateCreated() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIscarKmDirty()) {
	        if (this.getCarKm() != data.getCarKm())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsmechanicianControlDirty()) {
	        if (this.getMechanicianControl() != data.getMechanicianControl())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIscarRegNumberDirty()) {
	        if (this.getCarRegNumber() != null && data.getCarRegNumber() != null) {
	    	if (!this.getCarRegNumber().equals(data.getCarRegNumber())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getCarRegNumber() == null && data.getCarRegNumber() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsqualityControlDirty()) {
	        if (this.getQualityControl() != data.getQualityControl())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsoppdragNrDirty()) {
	        if (this.getOppdragNr() != data.getOppdragNr())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsmverkOrderNumberDirty()) {
	        if (this.getMverkOrderNumber() != null && data.getMverkOrderNumber() != null) {
	    	if (!this.getMverkOrderNumber().equals(data.getMverkOrderNumber())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getMverkOrderNumber() == null && data.getMverkOrderNumber() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsappSubtypeDirty()) {
	        if (this.getAppSubtype() != data.getAppSubtype())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsappSubtypeLimitDirty()) {
	        if (this.getAppSubtypeLimit() != null && data.getAppSubtypeLimit() != null) {
	    	if (!this.getAppSubtypeLimit().equals(data.getAppSubtypeLimit())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getAppSubtypeLimit() == null && data.getAppSubtypeLimit() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsappSubTypeStatusDirty()) {
	        if (this.getAppSubTypeStatus() != data.getAppSubTypeStatus())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIssoldHoursAmountDirty()) {
	        Double f1 = new Double(this.getSoldHoursAmount());
	        Double f2 = new Double(data.getSoldHoursAmount());
	        if (!f1.equals(f2))
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsholidayCodeDirty()) {
	        if (this.getHolidayCode() != null && data.getHolidayCode() != null) {
	    	if (!this.getHolidayCode().equals(data.getHolidayCode())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getHolidayCode() == null && data.getHolidayCode() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	    if (!data.getIsauthorizedDirty()) {
	        if (this.isAuthorized() != data.isAuthorized())
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    }
	    if (!data.getIsauthorizedDateDirty()) {
	        if (this.getAuthorizedDate() != null && data.getAuthorizedDate() != null) {
	    	if (!this.getAuthorizedDate().equals(data.getAuthorizedDate())) {
	    	    throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	    	}
	        } else if (!(this.getAuthorizedDate() == null && data.getAuthorizedDate() == null)) {
	    	throw new com.ibm.etools.ejb.client.runtime.FieldChangedException();
	        }
	    }
	}

	/**
	 * syncAppointmentData
	 */
	public no.moller.evp.model.ejb.AppointmentData syncAppointmentData(no.moller.evp.model.ejb.AppointmentData data) {
	    data.copyTo(this);
	    return this.getAppointmentData();
	}

	/**
	 * getPrimaryKey
	 */
	public Object getPrimaryKey() {
	    return getEntityContext().getPrimaryKey();
	}

	/**
	 * Get accessor for persistent attribute: mverkOrderNumber
	 */
	public java.lang.String getMverkOrderNumber()
	{
		return mverkOrderNumber;
	}

	/**
	 * Set accessor for persistent attribute: mverkOrderNumber
	 */
	public void setMverkOrderNumber(java.lang.String newMverkOrderNumber)
	{
		mverkOrderNumber = newMverkOrderNumber;
	}
	/**
	 * Get accessor for persistent attribute: appSubtypeLimit
	 */
	public java.lang.String getAppSubtypeLimit()
	{
		return appSubtypeLimit;
	}
	/**
	 * Set accessor for persistent attribute: appSubtypeLimit
	 */
	public void setAppSubtypeLimit(java.lang.String newAppSubtypeLimit)
	{
		appSubtypeLimit = newAppSubtypeLimit;
	}
	/**
	 * Get accessor for persistent attribute: appSubtype
	 */
	public int getAppSubtype()
	{
		return appSubtype;
	}
	/**
	 * Set accessor for persistent attribute: appSubtype
	 */
	public void setAppSubtype(int newAppSubtype)
	{
		appSubtype = newAppSubtype;
	}
	/**
	 * Get accessor for persistent attribute: appSubTypeStatus
	 */
	public int getAppSubTypeStatus()
	{
		return appSubTypeStatus;
	}
	/**
	 * Set accessor for persistent attribute: appSubTypeStatus
	 */
	public void setAppSubTypeStatus(int newAppSubTypeStatus)
	{
		appSubTypeStatus = newAppSubTypeStatus;
	}
	/**
	 * Get accessor for persistent attribute: soldHoursAmount
	 */
	public double getSoldHoursAmount()
	{
		return soldHoursAmount;
	}
	/**
	 * Set accessor for persistent attribute: soldHoursAmount
	 */
	public void setSoldHoursAmount(double newSoldHoursAmount)
	{
		soldHoursAmount = newSoldHoursAmount;
	}
	/**
	 * Get accessor for persistent attribute: holidayCode
	 */
	public java.lang.String getHolidayCode() {
		return holidayCode;
	}
	/**
	 * Set accessor for persistent attribute: holidayCode
	 */
	public void setHolidayCode(java.lang.String newHolidayCode) {
		holidayCode = newHolidayCode;
	}

	/**
	 * Get accessor for persistent attribute: authorized
	 */
	public boolean isAuthorized() {
		return authorized;
	}

	/**
	 * Set accessor for persistent attribute: authorized
	 */
	public void setAuthorized(boolean newAuthorized) {
		authorized = newAuthorized;
	}

	/**
	 * Get accessor for persistent attribute: authorizedDate
	 */
	public java.util.Date getAuthorizedDate() {
	    return authorizedDate;
	}

	/**
	 * Set accessor for persistent attribute: authorizedDate
	 */
	public void setAuthorizedDate(java.util.Date newAuthorizedDate) {
	    authorizedDate = newAuthorizedDate;
	}

	/**
	 * Get accessor for persistent attribute: hasVcoInSession
	 */
	public boolean isHasVcoInSession() {
	    return hasVcoInSession;
	}

	/**
	 * Set accessor for persistent attribute: hasVcoInSession
	 */
	public void setHasVcoInSession(boolean newHasVcoInSession) {
	    hasVcoInSession = newHasVcoInSession;
	}
}
